/**
 * Configuration for InteractiveBackground component
 * All visual and behavioral parameters in one place
 */

export const INTERACTIVE_BACKGROUND_CONFIG = {
  // Canvas setup
  NODE_SPACING: 60,
  MAX_CONNECTION_DISTANCE: 120,

  // Visual effects
  LINE_OPACITY: 0.08,
  NODE_OPACITY: 0.04,
  LINE_WIDTH: 0.8,
  NODE_RADIUS: 1.2,

  // Physics
  INFLUENCE_RADIUS_MULTIPLIER: 4.0,
  GRAVITY_DESKTOP: 12.0,
  GRAVITY_MOBILE: 8.0,
  MAX_DISPLACEMENT_DESKTOP: 60,
  MAX_DISPLACEMENT_MOBILE: 40,
  CURVE_INTENSITY_DESKTOP: 4.2,
  CURVE_INTENSITY_MOBILE: 3.2,

  // Performance
  PERFORMANCE_THRESHOLD_LINE: 0.001,
  PERFORMANCE_THRESHOLD_NODE: 0.02,
  CULL_MULTIPLIER: 1.5,

  // Animation
  FADE_OUT_DELAY: 800,
  MOBILE_BREAKPOINT: 768,
} as const;